install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "web-bakery/oxid-credit": "{{ .Data.global.composer.ref_name }}"
          },
          "repositories": {
            "web-bakery/oxid-credit": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/module-template.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:module:activate Playground_module-template

runscript: &runscript
  matrix:
    script: |
      [
        "module_template:tests-unit",
        "module_template:tests-integration",
        "module_template:tests-codeception"
      ]
  module_template:
    path: 'vendor/web-bakery/oxid-credit'

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "module_template:phpcs-report",
        "module_template:phpmd-report",
        "module_template:phpstan-report"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/web-bakery/oxid-credit/'
  project_key: 'CHANGE SONARCLOUD ORGANIZATION'
  project_name: 'web-bakery/oxid-credit'
  organization: 'CHANGE SONARCLOUD ORGANIZATION'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Dsonar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: 'Module template ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
