services:
  _defaults:
    public: false
    autowire: true

  WebBakery\Credit\Tracker\Repository\TrackerRepositoryInterface:
    class: WebBakery\Credit\Tracker\Repository\TrackerRepository
    public: true

  WebBakery\Credit\Tracker\Service\TrackerServiceInterface:
    class: WebBakery\Credit\Tracker\Service\TrackerService
    public: true

  WebBakery\Credit\Tracker\Subscriber\BeforeModelUpdate:
    class: WebBakery\Credit\Tracker\Subscriber\BeforeModelUpdate
    tags: [ 'kernel.event_subscriber' ]