services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("WebBakery\\Credit\\Core\\Registry").getRequest()'
      OxidEsales\Eshop\Core\Language: '@=service("WebBakery\\Credit\\Core\\Registry").getLang()'

  WebBakery\Credit\Greeting\Repository\GreetingRepositoryInterface:
    class: WebBakery\Credit\Greeting\Repository\GreetingRepository
    public: true

  WebBakery\Credit\Greeting\Service\GreetingMessageServiceInterface:
    class: WebBakery\Credit\Greeting\Service\GreetingMessageService
    public: true

  WebBakery\Credit\Greeting\Infrastructure\UserModelFactoryInterface:
    class: WebBakery\Credit\Greeting\Infrastructure\UserModelFactory

  WebBakery\Credit\Greeting\Service\UserServiceInterface:
    class: WebBakery\Credit\Greeting\Service\UserService
    public: true
