services:
  _defaults:
    public: false
    autowire: true

  WebBakery\Credit\Settings\Service\ModuleSettingsServiceInterface:
    class: WebBakery\Credit\Settings\Service\ModuleSettingsService
    public: true
